### ISSUE TITLE
how to upload other file rather than image only

### ISSUE THREAD

**Issue by Abhishekwayindia** [hasancse91/Android-File-Upload-To-Server#1]
I have followed your code but it helps  only to upload image to server. How come I can upload pdf/audio/video to server using this code.

**Comment by hasancse91** [comment]
> I have followed your code but it helps only to upload image to server. How come I can upload pdf/audio/video to server using this code.

I've updated the source code. Now you can upload any type of file. Pull from `master` branch and test. You can identify the changes from latest commits.

To enable any file type assign `false` to `isOnlyImageAllowed` variable in `MainActivity`.
