### ISSUE TITLE
It stops working

### ISSUE THREAD

**Issue by oyusufa** [hasancse91/Android-File-Upload-To-Server#2]
It stops working for me in android. It gives deprecated api usage error. can you solve it and post again? I have no idea with android programming but ı have to do this for my project. If you have a ready and stable project, can you upload it?

**Comment by hasancse91** [comment]
Can you share the crash report please? It'll be helpful for finding the issue.
Thanks.

**Comment by hasancse91** [comment]
And also let me know about your testing device configuration. I've just tested. It's working fine at my end.

**Comment by oyusufa** [comment]
I don't know anything about testing device configuration, can you explain it? Thanks a lot for helping me, ı will share crash report about 19 hours later.

**Comment by hasancse91** [comment]
> I don't know anything about testing device configuration, can you explain it?

I mean which Android device are you using for testing the App? I asked for Android version, Mobile Device company, RAM etc configurations.

**Comment by oyusufa** [comment]
I am using samsung j7 prime phone to test application, android version 28. I dont have a definite ram conf.

**Comment by hasancse91** [comment]
> I am using samsung j7 prime phone to test application, android version 28. I dont have a definite ram conf.

I didn't find anything wrong with this project. Can you please clone again the project and reinstall at your phone?

**Comment by oyusufa** [comment]
It says that it uses a deprecated api, recompile by using -Xlint

**Comment by oyusufa** [comment]
Application says that 
Response from Server:
CLEARTEXT communication to 192.***.*.*** not permitted by network security policy

**Comment by oyusufa** [comment]
I have changed some parameters according to https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted 
and it is now working

When I try to upload audio files, ı turned the isOnlyImageAllowed to false but I cannot choose any file in this mode, what should I do to send audio files for example

**Comment by hasancse91** [comment]
> I have changed some parameters according to https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted
> and it is now working
> 
> When I try to upload audio files, ı turned the isOnlyImageAllowed to false but I cannot choose any file in this mode, what should I do to send audio files for example

You did the correct things. Thanks for placing the issue. I've updated Manifest file to resolve the cleartext issue.
